version: 0.2

env:
  variables:
    FRONT_END_URL: 'http://localhost:8000/'

phases:
  pre_build:
    commands:
      - echo "Before installation"
      - cd backend/
      - pip install -r requirements.txt
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'backend'